namespace Crossoverse.Core.Domain.MotionCapture.FaceTracking
{
    /// <summary>
    /// ARKit Blend Shape Name
    /// </summary>
    public enum BlendShapeName
    {
        browDownLeft = 0,
        browDownRight = 1,
        browInnerUp = 2,
        browOuterUpLeft = 3,
        browOuterUpRight = 4,
        cheekPuff = 5,
        cheekSquintLeft = 6,
        cheekSquintRight = 7,
        eyeBlinkLeft = 8,
        eyeBlinkRight = 9,
        eyeLookDownLeft = 10,
        eyeLookDownRight = 11,
        eyeLookInLeft = 12,
        eyeLookInRight = 13,
        eyeLookOutLeft = 14,
        eyeLookOutRight = 15,
        eyeLookUpLeft = 16,
        eyeLookUpRight = 17,
        eyeSquintLeft = 18,
        eyeSquintRight = 19,
        eyeWideLeft = 20,
        eyeWideRight = 21,
        jawForward = 22,
        jawLeft = 23,
        jawOpen = 24,
        jawRight = 25,
        mouthClose = 26,
        mouthDimpleLeft = 27,
        mouthDimpleRight = 28,
        mouthFrownLeft = 29,
        mouthFrownRight = 30,
        mouthFunnel = 31,
        mouthLeft = 32,
        mouthLowerDownLeft = 33,
        mouthLowerDownRight = 34,
        mouthPressLeft = 35,
        mouthPressRight = 36,
        mouthPucker = 37,
        mouthRight = 38,
        mouthRollLower = 39,
        mouthRollUpper = 40,
        mouthShrugLower = 41,
        mouthShrugUpper = 42,
        mouthSmileLeft = 43,
        mouthSmileRight = 44,
        mouthStretchLeft = 45,
        mouthStretchRight = 46,
        mouthUpperUpLeft = 47,
        mouthUpperUpRight = 48,
        noseSneerLeft = 49,
        noseSneerRight = 50,
        tongueOut = 51,
        blendShapeCount = 52,
        unknown = -1,
    }
}